curl -H "Content-Type: text/xml" -X POST \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:moduleAdd xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.module.kernel.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><module xmlns="">inet</module><title xmlns="">Inet1</title></ns5:moduleAdd></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.kernel.module/ModuleService

curl -H "Content-Type: text/xml" -X POST \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:deviceTypeUpdate xmlns:common=" http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><arg0 xmlns="" activeConfigId="0" configId="0" deviceEntitySpecId="0" entityId="0" entitySpecId="0" id="-1" scriptId="0" title="RootDeviceType1: RootDevice1" uniqueInterfaces="false" xsi:type="ns5:inetDeviceType"><comment></comment><config></config><managmentType>0</managmentType><serviceActivationType>0</serviceActivationType><source>false</source><interfaceList></interfaceList></arg0></ns5:deviceTypeUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService

curl -H "Content-Type: text/xml" -X POST \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:inetDeviceUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><inetDevice xmlns="" deviceGroupIds="" deviceTypeId="1" entityId="0" entitySpecId="0" id="-1" ident="RootDevice1" orderManagerDisabled="false" parentId="0" title="RootDevice1"><entityAttributes></entityAttributes><comment></comment><config></config><host></host><password></password><secret></secret><username></username><invConfig></invConfig><invDeviceId>0</invDeviceId><invDeviceTypeId>1</invDeviceTypeId><invHost></invHost><invIdentifier>RootDevice1</invIdentifier></inetDevice><updateInvDevice xmlns="">true</updateInvDevice></ns5:inetDeviceUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService
