# Создаем экземпляр модуля inet
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:moduleAdd xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.module.kernel.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><module xmlns="">inet</module><title xmlns="">Интернет1</title></ns5:moduleAdd></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.kernel.module/ModuleService

# Создаем услугу
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:serviceUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.module.kernel.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><service xmlns="" id="-1" moduleId="1" title="Доступ в интернет" unit="30000" using="true"></service></ns5:serviceUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.kernel.module/ServiceService

# Создаем типы трафика
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:trafficTypeUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><traficType xmlns="" id="0" title="Входящий трафик" unit="30000"></traficType></ns5:trafficTypeUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetServService
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:trafficTypeUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><traficType xmlns="" id="0" title="Исходящий трафик" unit="30000"></traficType></ns5:trafficTypeUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetServService

# Создаем тип сервиса
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:inetServTypeUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><inetServType xmlns="" addressAllInterface="false" addressType="5" deviceGroupIds="1" deviceTypeIds="" id="0" needContractObject="false" needDevice="true" needIdentifier="false" needInterface="true" needLogin="false" needMacAddress="false" needRestriction="false" needVlan="false" parentTypeIds="" personalInterface="true" personalVlan="true" sessionCountLimit="1" sessionCountLimitLock="false" sessionInitiationType="0" title="DHCP" trafficTypeLinkId="0"><config>title.pattern=DHCP (${deviceIdentifier}):(${interfaceId})</config><ipFromParentRange>false</ipFromParentRange></inetServType></ns5:inetServTypeUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetServService

# Создаем тип для корневого устройства
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
 -d $'<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:deviceTypeUpdate xmlns:common=" http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><arg0 xmlns="" activeConfigId="0" configId="0" deviceEntitySpecId="0" entityId="0" entitySpecId="0" id="-1" scriptId="0" title="Access+Accounting" uniqueInterfaces="false" xsi:type="ns5:inetDeviceType"><comment></comment><config>dhcp.ipCategories=1\ndhcp.option.serverIdentifier=192.168.99.254\ndhcp.option.leaseTime=180</config><managmentType>0</managmentType><serviceActivationType>0</serviceActivationType><source>false</source><interfaceList></interfaceList></arg0></ns5:deviceTypeUpdate></S:Body></S:Envelope>' \
 http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService

# Создаем корневое устройство
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:inetDeviceUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><inetDevice xmlns="" deviceGroupIds="" deviceTypeId="1" entityId="0" entitySpecId="0" id="-1" ident="" orderManagerDisabled="false" parentId="0" title="IPoE1"><entityAttributes></entityAttributes><comment></comment><config></config><host></host><password></password><secret></secret><username></username><invConfig></invConfig><invDeviceId>0</invDeviceId><invDeviceTypeId>1</invDeviceTypeId><invHost></invHost><invIdentifier>IPoE1</invIdentifier></inetDevice><updateInvDevice xmlns="">true</updateInvDevice></ns5:inetDeviceUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService

# Создаем IP-ресурс
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:ipCategoryUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://common.resource.inventory.systems.oss.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><category xmlns="" id="0" parentId="0" title="192.168.200.0/24"></category></ns5:ipCategoryUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.oss.systems.inventory.resource/1/ResourceService
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:ipResourceUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://common.resource.inventory.systems.oss.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><resource xmlns="" addressFrom="wKjIAg==" addressTo="wKjI/g==" categoryId="1" dns="8.8.8.8" id="0" router="192.168.200.1" subnetMask="255.255.255.0"><comment></comment><config></config></resource><skipSubscriptionCheck xmlns="">true</skipSubscriptionCheck></ns5:ipResourceUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.oss.systems.inventory.resource/1/ResourceService

# Создаем группу для коммутаторов доступа
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:deviceGroupUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><arg0 xmlns="" id="-1" title="Коммутатор доступа"><cityId>0</cityId><comment></comment><parentId>0</parentId></arg0></ns5:deviceGroupUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService

# Создаем тип для коммутаторов доступа
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:deviceTypeUpdate xmlns:common=" http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><arg0 xmlns="" activeConfigId="0" configId="0" deviceEntitySpecId="0" entityId="0" entitySpecId="0" id="-1" scriptId="0" title="D-Link DES-3200-28 A1" uniqueInterfaces="false" xsi:type="ns5:inetDeviceType"><comment></comment><config></config><managmentType>0</managmentType><serviceActivationType>0</serviceActivationType><source>false</source><interfaceList></interfaceList></arg0></ns5:deviceTypeUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:deviceTypeUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><arg0 xmlns="" activeConfigId="0" configId="0" deviceEntitySpecId="0" entityId="0" entitySpecId="0" id="2" scriptId="0" title="D-Link DES-3200-28 A1" uniqueInterfaces="false" xsi:type="ns5:inetDeviceType"><comment></comment><config></config><managmentType>0</managmentType><serviceActivationType>0</serviceActivationType><source>false</source><interfaceList><interfaceList deviceTypeId="0" id="1" title="Порт 1"></interfaceList><interfaceList deviceTypeId="0" id="2" title="Порт 2"></interfaceList><interfaceList deviceTypeId="0" id="3" title="Порт 3"></interfaceList><interfaceList deviceTypeId="0" id="4" title="Порт 4"></interfaceList><interfaceList deviceTypeId="0" id="5" title="Порт 5"></interfaceList><interfaceList deviceTypeId="0" id="6" title="Порт 6"></interfaceList><interfaceList deviceTypeId="0" id="7" title="Порт 7"></interfaceList><interfaceList deviceTypeId="0" id="8" title="Порт 8"></interfaceList><interfaceList deviceTypeId="0" id="9" title="Порт 9"></interfaceList><interfaceList deviceTypeId="0" id="10" title="Порт 10"></interfaceList><interfaceList deviceTypeId="0" id="11" title="Порт 11"></interfaceList><interfaceList deviceTypeId="0" id="12" title="Порт 12"></interfaceList><interfaceList deviceTypeId="0" id="13" title="Порт 13"></interfaceList><interfaceList deviceTypeId="0" id="14" title="Порт 14"></interfaceList><interfaceList deviceTypeId="0" id="15" title="Порт 15"></interfaceList><interfaceList deviceTypeId="0" id="16" title="Порт 16"></interfaceList><interfaceList deviceTypeId="0" id="17" title="Порт 17"></interfaceList><interfaceList deviceTypeId="0" id="18" title="Порт 18"></interfaceList><interfaceList deviceTypeId="0" id="19" title="Порт 19"></interfaceList><interfaceList deviceTypeId="0" id="20" title="Порт 20"></interfaceList><interfaceList deviceTypeId="0" id="21" title="Порт 21"></interfaceList><interfaceList deviceTypeId="0" id="22" title="Порт 22"></interfaceList><interfaceList deviceTypeId="0" id="23" title="Порт 23"></interfaceList><interfaceList deviceTypeId="0" id="24" title="Порт 24"></interfaceList><interfaceList deviceTypeId="0" id="25" title="Порт 25"></interfaceList><interfaceList deviceTypeId="0" id="26" title="Порт 26"></interfaceList><interfaceList deviceTypeId="0" id="27" title="Порт 27"></interfaceList><interfaceList deviceTypeId="0" id="28" title="Порт 28"></interfaceList></interfaceList></arg0></ns5:deviceTypeUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService

# Создаем коммутатор доступа в библиотеке
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:deviceUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><arg0 xmlns="" deviceGroupIds="1" deviceTypeId="2" entityId="0" entitySpecId="0" id="-1" ident="10.252.0.32" orderManagerDisabled="false" parentId="1" title="10.252.0.32" xsi:type="ns5:invDevice"><entityAttributes></entityAttributes><comment></comment><config></config><host>10.252.0.32:23</host><password>admin</password><secret></secret><username>admin</username></arg0></ns5:deviceUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService

# Добавляем коммутатор доступа из библиотеки в дерево устройств
curl --header "Content-Type: text/xml" --request POST --silent --output /dev/null --write-out "%{http_code}\n" \
  -d '<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Header><auth xmlns="http://ws.base.kernel.bgbilling.bitel.ru/" pswd="admin" user="admin"></auth></S:Header><S:Body><ns5:inetDeviceUpdate xmlns:common="http://common.bitel.ru" xmlns:ns5="http://service.common.api.inet.modules.bgbilling.bitel.ru/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><inetDevice xmlns="" deviceTypeId="2" entityId="0" entitySpecId="0" id="0" ident="10.252.0.32" orderManagerDisabled="false" parentId="1"><comment></comment><config>ip.resource.categoryId=1</config><host>10.252.0.32:23</host><password>admin</password><secret></secret><username>admin</username><invConfig></invConfig><invDeviceId>2</invDeviceId><invDeviceTypeId>2</invDeviceTypeId><invHost>10.252.0.32</invHost><invIdentifier>10.252.0.32</invIdentifier></inetDevice><updateInvDevice xmlns="">false</updateInvDevice></ns5:inetDeviceUpdate></S:Body></S:Envelope>' \
  http://localhost:8080/bgbilling/executer/ru.bitel.bgbilling.modules.inet.api/1/InetDeviceService
