# Справочники -> Тарифные планы -> ТАРИФ -> Дерево
# Создаем помесячную абонентскую плату
module=tariff&action=ModifTariffNode&command=create&parent=19&mtree_id=5&type=month_mode
module=tariff&action=ModifTariffNode&command=update&data=mode%26month%25sid%262&id=20
