# Создаем помесячную абонентскую плату
module=tariff&action=ModifTariffNode&command=create&parent=6&mtree_id=2&type=month_mode
module=tariff&action=ModifTariffNode&command=update&data=mode%26month%25sid%262&id=7
