# Справочники -> Тарифные планы -> ТАРИФ -> Дерево
# Добавляем опцию
module=tariff&action=ModifTariffNode&command=create&parent=14&mtree_id=4&type=optionAdd
module=tariff&action=ModifTariffNode&command=update&data=inetOptionId%263&id=18
