# Справочники -> Тарифные планы -> ТАРИФ -> Дерево
# Добавляем стоимость
module=tariff&action=ModifTariffNode&command=create&parent=23&mtree_id=6&type=cost
module=tariff&action=ModifTariffNode&command=update&data=col%261%25cost%26100.0&id=24
