# Справочники -> Тарифные планы
module=tariff&action=AddTariffPlan&used=1
module=tariff&action=UpdateTariffPlan&tpid=3&face=0&title=L2-1&title_web=L2-1&use_title_in_web=0&values=&tpused=1&config=&mask=&
