FROM openjdk:8-jdk

${INC}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -qq update \
  && apt-get -qq install --yes unzip \
  && apt-get -qq clean \
  && wget --quiet $FTP_DATA_DIR/BGInetAccess_$BGINETACCESS_VERSION.zip \
  && unzip -qq BGInetAccess_$BGINETACCESS_VERSION.zip \
  && mv BGInetAccess $BGINETACCESS_HOME \
  && rm --force BGInetAccess_$BGINETACCESS_VERSION.zip \
  && chmod +x $BGINETACCESS_HOME/*.sh \
  && chmod +x $BGINETACCESS_HOME/script/* \
  && mkdir /opt/bgbilling \
  && ln -s $BGINETACCESS_HOME /opt/bgbilling/BGInetAccess \
  && ln -s $BGINETACCESS_HOME/script/bginet_access /etc/init.d/bginet_access \
  && update-rc.d bginet_access defaults \
  && rm --recursive --force /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD container/ $BGINETACCESS_HOME/

VOLUME $BGINETACCESS_HOME

EXPOSE 1812/udp
EXPOSE 67/udp

CMD $BGINETACCESS_HOME/bginetaccess.sh && tail -f /dev/null
